### Homework 3 Numpy Arrays

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into an numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [2]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


1. How can you get help on `np.array`?

Call `dir()` on `np.array`. 

Call `dir()` on `car`.

Note the difference. `car` has methods and attributes we can use.

In [4]:

help(np.array)
dir(np.array)
dir(car)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

2. What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [5]:
print(car.dtype)
print(mpg.dtype)
print(horsepower.dtype)
print(origin.dtype)

object
float64
float64
object


3. `numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [ ]:
#It is an alias or aliasing. It is done for speed and potential accuracy. Typing out numpy instead of np gives you plenty of extra fat finger
#mistake opportunities and np is so much faster than numpy. 

4. Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [10]:
print(car.ndim)
print(mpg.ndim)
print(cylinders.ndim)
print(displacement.ndim)
##and so on down the line

1
1
1
1


5. Show how to:

- multiply the `mpg` array by 12.
- divide the `mpg` array by 3.
- raise the `mpg` array to the power of 4.
- take the square root of the `mpg` array.

In [69]:
multiply_mpg = (mpg*12)
divide_mpg = (mpg/3)
powerful_mpg = (mpg**4)
root_mpg =  np.sqrt(mpg)



6. What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help)

In [94]:
hp_sum = np.sum(horsepower)
hp_min = np.min(horsepower)
hp_max = np.max(horsepower)
hp_median = np.median(horsepower)
from scipy import stats as st

hp_tricky_one = st.mode(horsepower)


7. Select a subset of `acceleration`. 

- Select only the first 5 elements.
- Select every other element (new selection).

In [71]:
acceleration_first_5 = acceleration[:5] # zero indexing plus the range excluding the last number means this is a 5. 
acceleration_everyother = acceleration[::2]



[12.  11.5 11.  12.  10.5]


8. Show how to select the number `99` in the array below. 

In [31]:
select_99 = np.array([[1,2,3],
                      [4,5,99]])

In [34]:
ninenine = select_99[1,2]
print(ninenine)

99


9. Select the last element in each subarray (do this with one operation.)

In [38]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])

select_even_more = select_more[:,2]
print(select_even_more)

[3 6 9]


10. Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [46]:
np.lookfor('log')
np.log(mpg)
print(np.log(mpg))


[2.89037176 2.7080502  2.89037176 2.77258872 2.83321334 2.7080502
 2.63905733 2.63905733 2.63905733 2.7080502        -inf       -inf
       -inf       -inf       -inf 2.7080502  2.63905733       -inf
 2.7080502  2.63905733 3.17805383 3.09104245 2.89037176 3.04452244
 3.29583687 3.25809654 3.21887582 3.17805383 3.21887582 3.25809654
 3.04452244 2.30258509 2.30258509 2.39789527 2.19722458 3.29583687
 3.33220451 3.21887582 3.21887582       -inf 2.94443898 2.77258872
 2.83321334 2.94443898 2.89037176 2.63905733 2.63905733 2.63905733
 2.63905733 2.48490665 2.56494936 2.56494936 2.89037176 3.09104245
 2.94443898 2.89037176 3.13549422 3.33220451 3.40119738 3.40119738
 3.4339872  3.55534806 3.29583687 3.25809654 3.17805383 3.21887582
 3.13549422 2.99573227 3.04452244 2.56494936 2.63905733 2.7080502
 2.63905733 2.83321334 2.39789527 2.56494936 2.48490665 2.56494936
 2.94443898 2.7080502  2.56494936 2.56494936 2.63905733 2.89037176
 3.09104245 3.04452244 3.25809654 3.09104245 3.33220451 3.135494

11. You your google skills to find the unique items in `origin`. (This may not have been covered in the readings.)

In [47]:
np.unique(origin)

array(['Europe', 'Japan', 'US'], dtype=object)

12. 
- Create a 2D array and print its shape as well as ndim. (Any shape is fine)

- Create a 3D array and print its shape as well as ndim.

- Create a 4D array and print its shape as well as ndim. *It's hard to visualize 4-Dimensions but numpy can do it with ease!*

In [60]:
two_d = np.array([["puppies", "cotton candy", "elmo"], ["kitten", "funnel cake", "big bird"], ["lizard", "fried twinkies", "Count"]])
print(two_d.shape)
print(two_d.ndim)

lucys_apartment = np.array([[["puppies", "cotton candy", "elmo"], ["kitten", "funnel cake", "big bird"], ["lizard", "fried twinkies", "Count"]],
  [["goldfish", "fried oreos", "bert"], ["snake", "corn dog", "ernie"], ["ferret", "sno cone", "Oscar the grouch"]], 
  [["beta fish", "lemonade", "cookie monster"], ["hamster", "soft pretzel", "Abby"], ["tiger cub", "turkey leg", "Snuffleupagus"]]])
print(lucys_apartment.shape)
print(lucys_apartment.ndim)

##having a rough time wrapping my brain around 4d so we're going with google's fine answer
wtf=np.zeros((2,2,2,2))
print(wtf.shape)
print(wtf.ndim)
                   

(3, 3)
2
(3, 3, 3)
3
4
(2, 2, 2, 2)


13.Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [63]:
print(origin =='US')

[ True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True False  True  True  True
 False False False False False False  True  True  True  True  True False
  True False  True False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True False False False
 False False False  True False  True False  True  True  True  True  True
  True  True  True  True  True  True False  True  True  True  True False
 False False False  True False False  True False  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True  True False  True False False  True
  True False  True  True False False False False  True False False  True
  True  True  True  True False  True False  True  True  True  True  True
  True  True  True  True False False False False False  True False False
 False False False  True  True  True  True  True  T

14. Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [68]:
Merica_only = car[origin=='US']
print(Merica_only)

['Chevrolet Chevelle Malibu' 'Buick Skylark 320' 'Plymouth Satellite'
 'AMC Rebel SST' 'Ford Torino' 'Ford Galaxie 500' 'Chevrolet Impala'
 'Plymouth Fury iii' 'Pontiac Catalina' 'AMC Ambassador DPL'
 'Chevrolet Chevelle Concours (sw)' 'Ford Torino (sw)'
 'Plymouth Satellite (sw)' 'AMC Rebel SST (sw)' 'Dodge Challenger SE'
 "Plymouth 'Cuda 340" 'Ford Mustang Boss 302' 'Chevrolet Monte Carlo'
 'Buick Estate Wagon (sw)' 'Plymouth Duster' 'AMC Hornet' 'Ford Maverick'
 'AMC Gremlin' 'Ford F250' 'Chevy C20' 'Dodge D200' 'Hi 1200D'
 'Chevrolet Vega 2300' 'Ford Pinto' 'AMC Gremlin'
 'Plymouth Satellite Custom' 'Chevrolet Chevelle Malibu' 'Ford Torino 500'
 'AMC Matador' 'Chevrolet Impala' 'Pontiac Catalina Brougham'
 'Ford Galaxie 500' 'Plymouth Fury iii' 'Dodge Monaco (sw)'
 'Ford Country Squire (sw)' 'Pontiac Safari (sw)'
 'AMC Hornet Sportabout (sw)' 'Chevrolet Vega (sw)' 'Pontiac Firebird'
 'Ford Mustang' 'Mercury Capri 2000' 'Plymouth Cricket'
 'Dodge Colt Hardtop' 'Chevrolet Vega' 'Ford

**The remaining questions are OPTIONAL**: The readings did not address all of these so you may have to use some "Google-Fu". 

1.What is an identity matrix? 
Create an identiy matrix of size 5 using an np method. 

In [93]:
# identity matrix is a square matrix where main diagonal is composed of 1 and others are zero. 
np.identity(5, dtype = None)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

2. Transpose the following array. 

In [74]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])


In [80]:
transposed_me = np.transpose(transpose_me)
print(transposed_me)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


3. Why does this multiplication operation fail? 

In [ ]:
arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])

arr1 * arr2

In [ ]:
#is it because they are different sizes? If I remember my linear algebra days there was something about them needing rows 
#to match columns or columns to match rows or something like that. 

Use numpy to answer the following questions. 

4. What is the average horsepower for `Europe` cars? (Hint: create boolean index of 'US' apply it to horsepower and perform the calculation.)

In [82]:
europe_only = np.average(horsepower[origin=='Europe'])
print(europe_only)



78.78082191780823


5. On average are Japanse cars more fuel efficient than US cars? 

In [89]:
Japan = np.average(mpg[origin == 'Japan'])
US = np.average(mpg[origin == 'US'])
if (Japan > US):
    print ("Yes , Japan is " + str(Japan) + " while US is "+ str(US))
else: 
    print("No, Japan is " + str(Japan) + " while US is "+ str(US))

Yes , Japan is 30.450632911392404 while US is 19.688188976377955


6. What is the correlation coefficient of `mpg` and `weight`?

In [90]:

print(np.corrcoef(mpg,weight))

[[ 1.         -0.78750994]
 [-0.78750994  1.        ]]


7. Why might you prefer an `np.array()` over a Python `list`? And when is a Python `list` preferred? 

In [ ]:
## a list is for when you need to use multiple data types. 
## originally when I learned about lists and arrays for pythons I couldn't imagine why anyone would use an array, but it seems
## like they are just as important as lists. WE've just shown exactly why we would use them over lists, so we can perform math
##on them. 